[package]
name = "primitives-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
eyre = "0.6.8"
primitive-types = "0.12.1"
rand = "0.8.5"
